### ISSUE TITLE
Live Preview doesn't update

### ISSUE THREAD

**Issue by frankharrison-wj** [verbb/super-table#117]
Hi

Live Preview doesn't seem to update when Super Table content within a Matrix is edited. Is there any way round this? I'm on Craft 2.6.2989, Super Table 1.0.5.

Otherwise love this plugin – thank you!

**Comment by brianlarson** [comment]
Noticing the same issue with Craft 3.0.0 RC10.1. Any plans to look into this? Or maybe this issues lies with Craft core? And great plugin indeed! Should be rolled into core as robust matrix-in-matrix is so often needed! Thanks!

**Comment by engram-design** [comment]
@frankharrison-wj I'm not seeing this on Craft 2.x with Super Table, and I've tried all the combinations possible. Are there are web console errors that pop up when you try to use Live Preview?

@brianlarson This is now fixed in the Craft 3.x version. Test it out via `composer require verbb/super-table:dev-craft-3` and it'll be rolled into the next update.

**Comment by brianlarson** [comment]
Thanks @engram-design! Worked a treat.

**Comment by frankharrison-wj** [comment]
Sorry @engram-design, looks like a found the solution to this back in October but forgot to update this thread. I had an error in my twig: I had `{% for row in block.accordion.rows %}` instead of `{% for row in block.accordion %}`, which seemed to work fine on the front-end but not in Live Preview. So not a bug in Super Table after all!
